import type { Metadata } from "next";
import Link from "next/link";
import { Check, Search, MapPin, Gauge, Sparkles } from "lucide-react";
import { getFAQSchema, getBreadcrumbSchema, SEO_CONSTANTS } from "@/lib/jsonld";
import { AuditForm } from "@/components/laie/AuditForm";

const { BASE_URL } = SEO_CONSTANTS;

/* ──────────────────────────────────────────────────────────────────────
   /laie/audit — free Google Business Profile + website audit lead magnet.
   Targets "gbp audit tool", "website seo audit tool free india".
   Top-of-funnel capture that routes into ERIX. WebApplication + FAQ schema.
─────────────────────────────────────────────────────────────────────── */

export const metadata: Metadata = {
  title: "Free Google Business Profile & Website Audit for Indian Businesses",
  description:
    "Get a free audit of your Google Business Profile, website SEO, and local visibility — powered by ECODrIx LAIE. See what's costing you leads, in minutes.",
  keywords: [
    "gbp audit tool",
    "google business profile audit",
    "website seo audit tool free india",
    "check my google business profile",
    "local seo audit india",
    "ECODrIx LAIE",
  ],
  alternates: { canonical: `${BASE_URL}/laie/audit` },
  openGraph: {
    title: "Free Google Business Profile & Website Audit | ECODrIx LAIE",
    description:
      "See what's costing you leads across your Google Business Profile and website — free, in minutes.",
    url: `${BASE_URL}/laie/audit`,
    type: "website",
  },
};

const CHECKS = [
  {
    icon: MapPin,
    t: "Google Business Profile",
    d: "Completeness, categories, reviews, posts, and NAP consistency across the web.",
  },
  {
    icon: Gauge,
    t: "Website & SEO health",
    d: "Core Web Vitals, mobile-friendliness, titles/meta, and indexability issues.",
  },
  {
    icon: Search,
    t: "Local visibility",
    d: "How you show up for the searches customers in your city actually use.",
  },
  {
    icon: Sparkles,
    t: "AI action plan",
    d: "A prioritized fix list generated by LAIE — what to fix first for the most leads.",
  },
];

const FAQS = [
  {
    q: "Is the audit really free?",
    a: "Yes. The Google Business Profile and website audit is free. You get a prioritized summary of issues; the full report and ongoing monitoring are available inside ECODrIx with a 14-day free trial.",
  },
  {
    q: "What does the audit check?",
    a: "It reviews your Google Business Profile (completeness, categories, reviews, NAP consistency), website SEO and Core Web Vitals, and how visible you are for local searches in your city — then generates an AI-prioritized fix list.",
  },
  {
    q: "How is this different from other SEO checkers?",
    a: "ECODrIx LAIE combines local (Google Business Profile) and website signals in one audit built for Indian SMBs, and turns findings into leads inside ERIX CRM — not just a score you have to act on manually.",
  },
  {
    q: "What happens after the audit?",
    a: "You get a clear action list. If you want, ECODrIx can help you fix and monitor issues, and LAIE can start finding new local leads and generating outreach that flows into your CRM.",
  },
];

export default function LaieAuditPage() {
  return (
    <div className="bg-background text-foreground min-h-screen overflow-x-hidden">
      <script
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: controlled JSON-LD data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            getBreadcrumbSchema([
              { name: "Home", url: "/" },
              { name: "LAIE", url: "/platform/lead-intelligence" },
              { name: "Free Audit", url: "/laie/audit" },
            ]),
          ),
        }}
      />
      <script
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: controlled JSON-LD data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebApplication",
            name: "ECODrIx LAIE Free Business Audit",
            url: `${BASE_URL}/laie/audit`,
            applicationCategory: "BusinessApplication",
            operatingSystem: "Web",
            description:
              "Free Google Business Profile and website SEO audit for Indian businesses, powered by ECODrIx LAIE.",
            offers: { "@type": "Offer", price: "0", priceCurrency: "INR" },
            publisher: { "@id": `${BASE_URL}/#organization` },
          }),
        }}
      />
      <script
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: controlled JSON-LD data
        dangerouslySetInnerHTML={{ __html: JSON.stringify(getFAQSchema(FAQS)) }}
      />

      {/* ── Hero ── */}
      <section className="pt-40 pb-16 px-6 relative overflow-hidden">
        <div
          className="absolute top-0 left-1/2 -translate-x-1/2 pointer-events-none w-[700px] h-[400px] blur-[14px] bg-[conic-gradient(from_270deg_at_50%_0%,transparent_55deg,color-mix(in_srgb,var(--color-warning)_20%,transparent)_85deg,color-mix(in_srgb,var(--color-warning)_7%,transparent)_115deg,transparent_155deg)]"
          aria-hidden
        />
        <div className="wrapper relative z-10">
          <nav
            aria-label="Breadcrumb"
            className="flex items-center gap-2 text-xs text-subtle mb-6"
          >
            <Link href="/" className="hover:text-foreground transition-colors">
              Home
            </Link>
            <span>/</span>
            <Link
              href="/platform/lead-intelligence"
              className="hover:text-foreground transition-colors"
            >
              LAIE
            </Link>
            <span>/</span>
            <span className="text-foreground">Free Audit</span>
          </nav>

          <div className="pill mb-6 text-warning border-warning/25 bg-warning/6">
            Free · Powered by LAIE
          </div>
          <h1 className="font-display font-black text-foreground mb-6 max-w-4xl text-[clamp(2.2rem,6vw,4rem)] tracking-[-0.04em] leading-[1.05]">
            Free Google Business Profile &amp; website audit.
          </h1>
          <p className="max-w-3xl leading-relaxed mb-8 text-[clamp(1rem,2vw,1.2rem)] text-muted-foreground">
            See exactly what's costing you leads — across your Google Business
            Profile, website SEO, and local visibility. ECODrIx LAIE audits it
            all and hands you a prioritized fix list in minutes.
          </p>

          {/* Functional lead capture — posts into the ECODrIx lead pipeline */}
          <AuditForm />
        </div>
      </section>

      {/* ── What we check ── */}
      <section className="py-20 px-6 sep-top bg-background">
        <div className="wrapper">
          <div className="pill mb-6">What we check</div>
          <h2 className="font-display font-black text-foreground mb-12 text-[clamp(1.8rem,4vw,2.8rem)] tracking-[-0.04em]">
            A complete local visibility check.
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {CHECKS.map(({ icon: Icon, t, d }) => (
              <div
                key={t}
                className="flex items-start gap-4 p-6 bg-surface border border-foreground/5 rounded-xl"
              >
                <div className="shrink-0 w-10 h-10 flex items-center justify-center bg-warning/8 border border-warning/25">
                  <Icon size={18} className="text-warning" />
                </div>
                <div>
                  <h3 className="text-foreground font-bold mb-1.5 text-base">
                    {t}
                  </h3>
                  <p className="text-subtle text-sm leading-relaxed">{d}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="py-20 px-6">
        <div className="wrapper">
          <div className="pill mb-6">Common questions</div>
          <h2 className="font-display font-black text-foreground mb-12 text-[clamp(1.8rem,4vw,2.8rem)] tracking-[-0.04em]">
            About the free audit.
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-foreground/5">
            {FAQS.map(({ q, a }) => (
              <div key={q} className="p-8 bg-surface">
                <h3 className="text-foreground font-bold mb-3 text-base flex items-start gap-2">
                  <Check size={16} className="shrink-0 mt-1 text-warning" />
                  {q}
                </h3>
                <p className="text-subtle text-sm leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
