import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "ECODrIx Privacy Policy. Learn how we collect, use, and protect your data. Industry-standard encryption, secure storage, and transparent data practices.",
  alternates: { canonical: "https://ecodrix.com/privacy" },
  openGraph: {
    title: "Privacy Policy | ECODrIx",
    description:
      "Learn how ECODrIx collects, uses, and protects your data with industry-standard encryption and secure storage.",
    url: "https://ecodrix.com/privacy",
    type: "website",
  },
};

export default function PrivacyPolicy() {
  return (
    <div className="w-full max-w-7xl mx-auto px-4 md:px-8">
      <div className="pt-32 pb-24 lg:pt-40 lg:pb-32">
        <div className="w-full max-w-full">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-[#64647A] hover:text-white transition-colors mb-12"
          >
            <ArrowLeft size={16} />
            Back to Home
          </Link>

          <div className="mb-16">
            <h1 className="text-4xl lg:text-5xl font-display font-black text-white tracking-tight mb-4">
              Privacy Policy
            </h1>
            <p className="text-[#64647A]">
              Last updated:{" "}
              {new Date().toLocaleDateString("en-US", {
                month: "long",
                year: "numeric",
              })}
            </p>
          </div>

          <div className="prose prose-invert prose-p:text-[#A8A8B3] prose-p:leading-relaxed prose-headings:text-white prose-headings:font-display prose-headings:font-bold prose-a:text-primary max-w-none">
            <h2>1. Information We Collect</h2>
            <p>
              We collect information that you provide directly to us when you
              register for an account, use our services, or communicate with us.
              This may include your name, email address, company name, phone
              number, and any other information you choose to provide.
            </p>
            <p>
              When you use our unified business infrastructure platform, we also
              collect data generated by your usage, including interaction logs,
              automation trigger history, and connected third-party account
              metadata.
            </p>

            <h2>2. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul>
              <li>Provide, maintain, and improve our services.</li>
              <li>Process transactions and send related information.</li>
              <li>
                Send technical notices, updates, security alerts, and support
                messages.
              </li>
              <li>Respond to your comments, questions, and requests.</li>
            </ul>

            <h2>3. Information Sharing</h2>
            <p>
              We do not share your personal information with third parties
              except as described in this privacy policy. We may share your
              information with vendors, consultants, and other service providers
              who need access to such information to carry out work on our
              behalf.
            </p>

            <h2>4. Data Security</h2>
            <p>
              We take reasonable measures to help protect information about you
              from loss, theft, misuse, unauthorized access, disclosure,
              alteration, and destruction. Your data is stored securely using
              industry-standard encryption.
            </p>

            <h2>5. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please
              contact us at:{" "}
              <a href="mailto:privacy@ecodrix.com">privacy@ecodrix.com</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
